// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

syntax = "proto3";

package arrow.adapter.protobuf;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option java_package = "org.apache.arrow.adapter.protobuf";
option java_outer_classname = "TestProtos";

enum Color {
  COLOR_UNSPECIFIED = 0;
  RED = 1;
  GREEN = 2;
}

enum Shape {
  SHAPE_UNSPECIFIED = 0;
  CIRCLE = 1;
  SQUARE = 2;
}

enum Size {
  option allow_alias = true;
  SIZE_UNSPECIFIED = 0;
  SMALL = 1;
  LARGE = 2;
  BIG = 2;
}

message Scalars {
  bool bool_field = 1;
  int32 int32_field = 2;
  sint32 sint32_field = 3;
  sfixed32 sfixed32_field = 4;
  uint32 uint32_field = 5;
  fixed32 fixed32_field = 6;
  int64 int64_field = 7;
  sint64 sint64_field = 8;
  sfixed64 sfixed64_field = 9;
  uint64 uint64_field = 10;
  fixed64 fixed64_field = 11;
  float float_field = 12;
  double double_field = 13;
  string string_field = 14;
  bytes bytes_field = 15;
}

message Item {
  string name = 1;
  int64 quantity = 2;
}

message Presence {
  int32 implicit_field = 1;
  optional int32 optional_field = 2;
  Item message_field = 3;
  oneof choice {
    string text = 4;
    Item item = 5;
  }
}

message Containers {
  repeated int32 ints = 1;
  repeated Item items = 2;
  map<string, int64> counts = 3;
  map<int32, Item> items_by_id = 4;
  map<bool, double> flags = 5;
  map<uint64, bytes> blobs = 6;
}

message Enums {
  Color color = 1;
  Shape shape = 2;
  repeated Color colors = 3;
  map<string, Color> colors_by_name = 4;
  optional Color optional_color = 5;
}

message Drawing {
  Shape shape = 1;
  Size size = 2;
}

message WellKnownTypes {
  google.protobuf.Timestamp timestamp = 1;
  google.protobuf.Struct struct = 2;
  google.protobuf.Value value = 3;
  google.protobuf.ListValue list_value = 4;
  repeated google.protobuf.Timestamp timestamps = 5;
  map<string, google.protobuf.Value> values = 6;
}

message Ping {
  Pong pong = 1;
}

message Pong {
  repeated Ping pings = 1;
}

message Envelope {
  string id = 1;
  Ping ping = 2;
}

message Node {
  map<string, Node> children = 1;
}
